# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field_of_work',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
