# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160925_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
