# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160925_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateofbirth',
            field=models.DateField(default=datetime.datetime(2016, 9, 25, 17, 21, 34, 805270, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='field_of_work',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team_members',
            field=models.ManyToManyField(to='users.UserProfile'),
        ),
    ]
