# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 16:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160927_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='year',
            new_name='from_date',
        ),
        migrations.AddField(
            model_name='project',
            name='to_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 9, 27, 16, 28, 22, 827422, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
