# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20160927_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='activities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='class_of',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='from_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='job',
            name='to_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
